"""
Triangle, pentagonal, and hexagonal numbers are generated by the following
formulae:

Triangle         Tn=n(n+1)/2         1, 3, 6, 10, 15, ...
Pentagonal         Pn=n(3n-1)/2         1, 5, 12, 22, 35, ...
Hexagonal         Hn=n(2n-1)         1, 6, 15, 28, 45, ...

It can be verified that T_285 = P_165 = H_143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""


def run():
    """
    Solution: Build a large set of all three kinds of numbers, then loop to
    check common membership in all of them.
    """
    N = 100000
    tn, pn, hn = set(), set(), set()
    for n in xrange(1, N):
        tn.add(n * (n + 1) / 2)
        pn.add(n * (3 * n - 1) / 2)
        hn.add(n * (2 * n - 1))

    for n in tn:
        if n > 40755 and n in pn and n in hn:
            return n
