/*
Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
*/

#include <iostream>
using namespace std;

/**
 * Solution: construct the fibseq up to 4 million while adding up the even terms
 */
int main(void) {
	int a = 1;
	int b = 1;
	int c = a + b;
	int total = 0;
	while (c < 4000000) {
		if (c % 2 == 0) {
			total += c;
		}
		a = b;
		b = c;
		c = a + b;
	}
	cout << total;
	return 0;
}
